Repository cozy-mate/cozymate-iOS, pull requests merged in 2024-08, with the labels that each got.

#1 [feat] Token 사용을 위한 AsyncStorage 설정
  ios/Podfile.lock
  ios/cozymate/PrivacyInfo.xcprivacy
  package.json
  src/utils/token.ts
  yarn.lock
Labels: 🎉 FEAT

#2 [feat] 코지홈 스크린 - 초대코드로 방만들기
  AppInner.tsx
  ios/Podfile.lock
  package.json
  src/assets/characterItem/10.svg
  src/assets/characterItem/13.svg
  src/assets/characterItem/14.svg
  src/assets/characterItem/15.svg
  src/assets/characterItem/4.svg
  src/assets/characterItem/5.svg
  src/assets/characterItem/6.svg
  src/assets/characterItem/7.svg
  src/assets/characterItem/8.svg
  src/assets/characterItem/9.svg
  src/assets/createRoom/copyIcon.svg
  src/recoil/recoil.ts
  src/recoil/type.ts
  src/screens/createRoom/completeCreate.tsx
  src/screens/createRoom/createRoom.tsx
  src/screens/createRoom/selectCharacter.tsx
  src/type/param/loginStack.ts
  src/utils/clipboard.ts
  yarn.lock
Labels: 🎉 FEAT

#4 [COZY-168] 피드 뷰 완성, 이미지 업로드 기능, 삭제 모달 구현
  android/app/src/debug/AndroidManifest.xml
  index.js
  ios/Podfile.lock
  ios/cozymate.xcodeproj/project.pbxproj
  ios/cozymate.xcodeproj/xcshareddata/xcschemes/Development.xcscheme
  ios/cozymate/Info.plist
  package.json
  src/assets/feedCreate/imageDeleteIcon.svg
  src/components/common/buttonModal.tsx
  src/components/createRoom/additionalInfomation.tsx
  src/components/createRoom/essentialInfomation.tsx
  src/components/feedMain/postCard.tsx
  src/components/feedMain/postList.tsx
  src/components/feedView/commentCard.tsx
  src/components/feedView/commentList.tsx
  src/components/feedView/controlModal.tsx
  src/hooks/useButtonModal.tsx
  src/hooks/useFeedModal.tsx
  src/hooks/useImageCarousel.tsx
  src/hooks/usePersonaImage.tsx
  src/screens/feed/feedCreate.tsx
  src/screens/feed/feedEdit.tsx
  src/screens/feed/feedMain.tsx
  src/screens/feed/feedView.tsx
  yarn.lock
Labels: 🎉 FEAT

#6 [COZY-176] 피드 API 연결
  ios/cozymate.xcodeproj/project.pbxproj
  src/assets/feedMain/feedEdit.svg
  src/components/feedView/commentCard.tsx
  src/components/feedView/controlModal.tsx
  src/recoil/recoil.ts
  src/screens/feed/feedCreate.tsx
  src/screens/feed/feedEdit.tsx
  src/screens/feed/feedMain.tsx
  src/screens/feed/feedView.tsx
  src/server/api/comment.ts
  src/server/api/feed.ts
  src/server/api/image.ts
  src/server/api/post.ts
  src/server/requestTypes/comment.ts
  src/server/requestTypes/feed.ts
  src/server/requestTypes/post.ts
  src/server/responseTypes/comment.ts
  src/server/responseTypes/feed.ts
  src/server/responseTypes/image.ts
  src/server/responseTypes/post.ts
  src/type/feed/feedType.ts
  src/type/feed/postType.ts
  src/type/param/loginStack.ts
Labels: 🎉 FEAT

#7 [COZY-189] feat: 화면 바깥 클릭 시 focus 해제 / back navigation 외 기타 수정 사항들
  ios/cozymate.xcodeproj/project.pbxproj
  src/components/feedMain/postCard.tsx
  src/components/feedView/commentCard.tsx
  src/layout/backCleanHeader.tsx
  src/screens/feed/feedCreate.tsx
  src/screens/feed/feedEdit.tsx
  src/screens/feed/feedMain.tsx
  src/screens/feed/feedView.tsx
  src/server/api/comment.ts
  src/server/requestTypes/comment.ts
  src/server/requestTypes/post.ts
  src/server/responseTypes/comment.ts
  src/server/responseTypes/post.ts
Labels: 🎉 FEAT

#8 [feat] 전체적인 API 연결 및 코드 수정
  .eslintrc
  AppInner.tsx
  babel.config.js
  ios/cozymate.xcodeproj/project.pbxproj
  ios/cozymate/Info.plist
  package.json
  src/components/common/customCheckInputBox.tsx
  src/components/common/customTextInputBox.tsx
  src/components/common/customTextarea.tsx
  src/components/customCheckBox.tsx
  src/components/customRadioBox.tsx
  src/components/navBar.tsx
  src/components/onBoard/dateSelectModal.tsx
  src/components/roomMate/checkBoxContainer.tsx
  src/components/roomMate/sameAnswerContainer.tsx
  src/components/roomMate/similarLifeStyleContainer.tsx
  src/components/todoList/customCalendar.tsx
  src/components/todoList/daySelect.tsx
  src/components/todoList/myRoleBox.tsx
  src/components/todoList/othersTodoBox.tsx
  src/components/todoList/roleBox.tsx
  src/components/todoList/ruleBox.tsx
  src/components/todoList/submitButton.tsx
  src/components/todoList/todoBox.tsx
  src/components/userDetail/listView.tsx
  src/components/userDetail/tableView.tsx
  src/recoil/recoil.ts
  src/recoil/type.ts
  src/screens/cozyHome/cozyHome.tsx
  src/screens/feed/feedMain.tsx
  src/screens/hasRoomMain.tsx
  src/screens/main.tsx
  src/screens/onBoard/complete.tsx
  src/screens/onBoard/personalInfo.tsx
  src/screens/roomMate/roomMate.tsx
  src/screens/signIn/signIn.tsx
  src/screens/todoList/createTodo.tsx
  src/screens/todoList/todoList.tsx
  src/screens/userDetail/userDetail.tsx
  src/server/api/member-stat.ts
  src/server/api/role.ts
  src/server/api/room-log.ts
  src/server/api/rule.ts
  src/server/api/todo.ts
  src/server/requestTypes/role.ts
  src/server/requestTypes/rule.ts
  src/server/requestTypes/todo.ts
  src/server/responseTypes/member-stat.ts
  src/server/responseTypes/role.ts
  src/server/responseTypes/room.ts
  src/server/responseTypes/rule.ts
  src/server/responseTypes/todo.ts
  src/type/param/roomStack.ts
  src/type/userDetail/userDetail.ts
  tailwind.config.js
  tsconfig.json
  yarn.lock
Labels: 🎉 FEAT

#10 [feat] React-Query 적용
  App.tsx
  AppInner.tsx
  ios/cozymate.xcodeproj/project.pbxproj
  package.json
  src/assets/lifeStyle/exampleImage.svg
  src/components/customCheckBox.tsx
  src/components/loading/loading.tsx
  src/components/roomMate/checkBoxContainer.tsx
  src/hooks/api/member-stat.ts
  src/hooks/api/role.ts
  src/hooks/api/room-log.ts
  src/hooks/api/rule.ts
  src/hooks/api/todo.ts
  src/screens/createRoom/createRoom.tsx
  src/screens/lifeStyle/basicInformation.tsx
  src/screens/lifeStyle/essentialInformation.tsx
  src/screens/lifeStyle/onBoarding.tsx
  src/screens/roomMain/roomMain.tsx
  src/screens/roomMate/roomMate.tsx
  src/screens/todoList/createTodo.tsx
  src/screens/todoList/dummyData.tsx
  src/screens/todoList/todoList.tsx
  src/screens/userDetail/userDetail.tsx
  yarn.lock
Labels: 🎉 FEAT

#12 [feat] 두번째 QA 및 바텀 내비게이션 아이콘 설정
  package.json
  src/assets/main/cozyHomeNotSelected.svg
  src/assets/main/cozyHomeSelected.svg
  src/assets/main/feedNotSelected.svg
  src/assets/main/feedSelected.svg
  src/assets/main/myPageNotSelected.svg
  src/assets/main/myPageSelected.svg
  src/assets/main/roleNRuleNotSelected.svg
  src/assets/main/roleNRuleSelected.svg
  src/assets/main/roomMateNotSelected.svg
  src/assets/main/roomMateSelected.svg
  src/components/common/customTextInputBox.tsx
  src/layout/bottomNavBar.tsx
  src/recoil/type.ts
  src/screens/hasRoomMain.tsx
  src/screens/lifeStyle/basicInformation.tsx
  src/screens/main.tsx
  src/screens/roomMain/roomMain.tsx
  src/screens/roomMate/roomMate.tsx
  src/screens/signIn/signIn.tsx
  src/screens/userDetail/userDetail.tsx
  src/server/requestTypes/member-stat.ts
  src/type/userDetail/userDetail.ts
  yarn.lock
Labels: 🐞 FIX, 🎉 FEAT

#13 [COZY-213] feat: ID를 사용한 수동 로그인
  ios/cozymate.xcodeproj/project.pbxproj
  package.json
  src/hooks/api/member.ts
  src/screens/signIn/signIn.tsx
Labels: 🎉 FEAT

#14 [feat] 3번째 QA 반영
  ios/cozymate.xcodeproj/project.pbxproj
  src/assets/main/roomMateNotSelected.svg
  src/assets/main/roomMateSelected.svg
  src/assets/roomMain/background.svg
  src/assets/roomMate/background.svg
  src/assets/todoList/background.svg
  src/assets/userDetail/background.svg
  src/screens/cozyHome/cozyHome.tsx
  src/screens/joinRoom/joinRoom.tsx
  src/screens/myPage/myPage.tsx
  src/screens/onBoard/complete.tsx
  src/screens/roomMain/roomMain.tsx
  src/screens/signIn/signIn.tsx
  src/screens/todoList/todoList.tsx
  src/server/api/room.ts
Labels: 🎉 FEAT

#15 [COZY-215] FCM 구현 완료(수신만 받으면 됨)
  index.js
  ios/Podfile
  ios/Podfile.lock
  ios/cozymate/AppDelegate.mm
  ios/cozymate/Info.plist
  ios/cozymate/PrivacyInfo.xcprivacy
  ios/cozymate/cozymateDebug.entitlements
  ios/cozymate/cozymateRelease.entitlements
  package.json
  src/hooks/useInitFcm.tsx
  src/screens/cozyHome/cozyHome.tsx
  src/screens/myPage/myPage.tsx
  src/screens/roomMain/roomMain.tsx
  src/server/api/fcm.ts
  src/server/requestTypes/fcm.ts
  src/server/responseTypes/fcm.ts
  src/utils/fcm.ts
  yarn.lock
Labels: 🎉 FEAT

#16 [COZY-219] feat: FCM 긴급 수정
  AppInner.tsx
  ios/cozymate.xcodeproj/project.pbxproj
  src/hooks/useInitFcm.tsx
  src/screens/roomMain/roomMain.tsx
  src/screens/signIn/signIn.tsx
Labels: 🎉 FEAT

#17 [feat] 이미지 SVG 사용하도록 수정 (S3 X)
  AppInner.tsx
  ios/cozymate.xcodeproj/project.pbxproj
  ios/cozymate/cozymate.entitlements
  src/assets/roomMate/downToggle.svg
  src/assets/roomMate/rightToggle.svg
  src/assets/roomMate/toggle.svg
  src/components/roomMate/sameAnswerContainer.tsx
  src/components/roomMate/similarLifeStyleContainer.tsx
  src/components/todoList/myRoleBox.tsx
  src/components/todoList/othersTodoBox.tsx
  src/components/todoList/roleBox.tsx
  src/components/waitingRoom/RoomMateBox.tsx
  src/hooks/useInitFcm.tsx
  src/screens/createRoom/completeCreate.tsx
  src/screens/createRoom/createRoom.tsx
  src/screens/myPage/myPage.tsx
  src/screens/onBoard/complete.tsx
  src/screens/roomMain/roomMain.tsx
  src/screens/roomMate/roomMate.tsx
  src/screens/signIn/signIn.tsx
  src/screens/userDetail/userDetail.tsx
  src/screens/waitingRoom/waitingRoom.tsx
  src/utils/profileImage.tsx
Labels: 🎉 FEAT

#18 [feat] 긴급 QA 수정
  AppInner.tsx
  ios/cozymate.xcodeproj/project.pbxproj
  package.json
  src/assets/characterItem/1.svg
  src/assets/characterItem/10.svg
  src/assets/characterItem/11.svg
  src/assets/characterItem/12.svg
  src/assets/characterItem/13.svg
  src/assets/characterItem/14.svg
  src/assets/characterItem/15.svg
  src/assets/characterItem/16.svg
  src/assets/characterItem/2.svg
  src/assets/characterItem/3.svg
  src/assets/characterItem/4.svg
  src/assets/characterItem/5.svg
  src/assets/characterItem/6.svg
  src/assets/characterItem/7.svg
  src/assets/characterItem/8.svg
  src/assets/characterItem/9.svg
  src/assets/chatting/grayRightArrow.svg
  src/assets/roomMate/downToggle.svg
  src/assets/roomMate/rightToggle.svg
  src/components/common/customCheckInputBox.tsx
  src/components/customRadioBox.tsx
  src/components/todoList/customCalendar.tsx
  src/hooks/api/chat-room.ts
  src/hooks/api/member.ts
  src/hooks/api/notification.ts
  src/hooks/api/role.ts
  src/hooks/api/room-log.ts
  src/hooks/api/rule.ts
  src/hooks/api/todo.ts
  src/screens/chatting/chat.tsx
  src/screens/cozyHome/cozyHome.tsx
  src/screens/createRoom/createRoom.tsx
  src/screens/createRoom/selectCharacter.tsx
  src/screens/joinRoom/joinRoom.tsx
  src/screens/lifeStyle/additionalInformation.tsx
  src/screens/lifeStyle/essentialInformation.tsx
  src/screens/myPage/myPage.tsx
  src/screens/notification/notification.tsx
  src/screens/onBoard/character.tsx
  src/screens/onBoard/complete.tsx
  src/screens/roomMain/roomMain.tsx
  src/screens/todoList/createTodo.tsx
  src/server/api/chat-room.ts
  src/server/api/chat.ts
  src/server/api/notification.ts
  src/server/requestTypes/chat.ts
  src/server/responseTypes/chat-room.ts
  src/server/responseTypes/chat.ts
  src/server/responseTypes/notification.ts
  src/type/param/loginStack.ts
  src/type/param/roomStack.ts
  src/utils/profileImage.tsx
  yarn.lock
Labels: 🎉 FEAT

#19 [COZY-222] refactor: FCM deviceId 진짜 고유하게, 피드 QA 반영
  index.js
  ios/Podfile.lock
  ios/cozymate/PrivacyInfo.xcprivacy
  package.json
  src/hooks/useInitFcm.tsx
  src/screens/feed/feedCreate.tsx
  src/screens/feed/feedEdit.tsx
  src/screens/feed/feedView.tsx
  src/screens/signIn/signIn.tsx
  src/utils/time/timeUtil.tsx
  yarn.lock
Labels: 🐞 FIX, 🔨 REFACTOR

#21 [COZY-233] 피드 상세보기 댓글 개수 반영
  src/screens/feed/feedView.tsx
  src/server/responseTypes/post.ts
Labels: 🐞 FIX

#23 [fix] 라이프 스타일 유무로 룸메이트 스크린 분리 및 각종 콘솔 제거, 카카오 로그인 수정
  src/hooks/api/member.ts
  src/hooks/useInitFcm.tsx
  src/screens/lifeStyle/additionalInformation.tsx
  src/screens/main.tsx
  src/screens/roomMain/roomMain.tsx
Labels: 🐞 FIX

#24 [COZY-238] FCM Background, Quit 받는 데이터 형식 수정
  index.js
Labels: 🎉 FEAT

#25 [feat] 기종에 따른 스타일 수정
  src/components/todoList/othersTodoBox.tsx
  src/hooks/device.ts
  src/layout/bottomNavBar.tsx
  src/screens/main.tsx
  src/screens/myPage/myPage.tsx
  src/screens/signIn/signIn.tsx
  src/screens/todoList/todoList.tsx
Labels: 🎉 FEAT
