Repository cozy-mate/cozymate-iOS, pull requests merged in 2024-12, with the labels that each got.

#65 [COZY-415] 토스트 팝업 추가
  .eslintrc
  App.tsx
  AppInner.tsx
  babel.config.js
  ios/cozymate.xcodeproj/project.pbxproj
  package.json
  src/assets/toast/toastCheck.svg
  src/assets/toast/toastFail.svg
  src/components/cozyHome/requestUserComponent.tsx
  src/config/toastConfig.tsx
  src/hooks/api/room.ts
  src/screens/cozyHome/cozyHome.tsx
  src/screens/roomDetail/roomDetail.tsx
  src/screens/userDetail/userDetail.tsx
  src/utils/toast.tsx
  tailwind.config.js
  tsconfig.json
  yarn.lock
Labels: 🎉 FEAT

#66 [COZY-419] 추가 QA 반영 및 코드 수정
  AppInner.tsx
  src/assets/roleNrule/background.svg
  src/assets/roleNrule/doneTodoBoxIcon.svg
  src/assets/roleNrule/notSelectedCheckBox.svg
  src/assets/roleNrule/plusButton.svg
  src/assets/roleNrule/selectedCheckBox.svg
  src/assets/roleNrule/settingIcon.svg
  src/assets/roleNrule/todoBoxIcon.svg
  src/components/cozyHome/recommendUser.tsx
  src/components/cozyHome/recommentUserList.tsx
  src/components/myPage/favoriteRoom.tsx
  src/components/myPage/favoriteUser.tsx
  src/components/roleNrule/customCalendar.tsx
  src/components/roleNrule/daySelect.tsx
  src/components/roleNrule/myRoleBox.tsx
  src/components/roleNrule/othersTodoBox.tsx
  src/components/roleNrule/roleBox.tsx
  src/components/roleNrule/roleNruleNav.tsx
  src/components/roleNrule/roleSelectMate.tsx
  src/components/roleNrule/ruleBox.tsx
  src/components/roleNrule/selectMate.tsx
  src/components/roleNrule/submitButton.tsx
  src/components/roleNrule/todoBox.tsx
  src/components/roomDetail/memberComponent.tsx
  src/components/roomMate/userComponent.tsx
  src/hooks/api/member.ts
  src/hooks/api/room-log.ts
  src/hooks/api/room-recommend.ts
  src/hooks/api/room.ts
  src/hooks/autoLogin.ts
  src/screens/chatting/chatRoom.tsx
  src/screens/joinRoom/joinRoom.tsx
  src/screens/myPage/withdraw.tsx
  src/screens/notification/notification.tsx
  src/screens/roleNrule/createRoleNRule.tsx
  src/screens/roleNrule/editRoleAndRule.tsx
  src/screens/roleNrule/roleNrule.tsx
  src/screens/roomDetail/roomDetail.tsx
  src/screens/roomMain/roomMain.tsx
  src/screens/schoolAuthentication/schoolAuthentication.tsx
  src/server/api/member.ts
  src/server/responseTypes/favorite.ts
  src/server/responseTypes/member-stat.ts
  src/server/responseTypes/member.ts
  src/utils/getLifeStyleIcon.tsx
Labels: 🐞 FIX, 🎉 FEAT

#68 [COZY-436] QA 반영
  App.tsx
  package.json
  src/assets/notification/noNotification.svg
  src/assets/userDetail/blur.jpg
  src/components/commonComponents/loading.tsx
  src/components/cozyHome/recommendRoom.tsx
  src/components/cozyHome/recommendRoomList.tsx
  src/components/cozyHome/recommentUserList.tsx
  src/components/onBoard/univInfoSelect.tsx
  src/components/recommendRoom/RoomComponent.tsx
  src/components/recommendRoom/roomComponent.tsx
  src/components/roleNrule/daySelect.tsx
  src/components/roomMate/filteringModal.tsx
  src/components/userDetail/tableView.tsx
  src/hooks/api/room.ts
  src/screens/createRoom/completeCreate.tsx
  src/screens/createRoom/createRoom.tsx
  src/screens/editRoom/editRoom.tsx
  src/screens/editRoom/selectCharacterModal.tsx
  src/screens/myPage/basicInfoUpdate.tsx
  src/screens/myPage/inquiry.tsx
  src/screens/notification/notification.tsx
  src/screens/recommendRoom/recommendRoom.tsx
  src/screens/roleNrule/createRoleNRule.tsx
  src/screens/roleNrule/editRoleAndRule.tsx
  src/screens/roomDetail/roomDetail.tsx
  src/screens/roomMain/roomMain.tsx
  src/screens/roomMate/roomMate.tsx
  src/screens/schoolAuthentication/schoolAuthentication.tsx
  src/screens/signIn/signIn.tsx
  src/server/api/room.ts
  src/server/api/rule.ts
  src/server/requestTypes/role.ts
  src/server/responseTypes/room.ts
  src/zustand/room/room.ts
  tailwind.config.js
  yarn.lock
Labels: 🐞 FIX

#70 [COZY-442] 추가 QA
  src/assets/recommendRoom/check.svg
  src/assets/recommendRoom/colorCheck.svg
  src/components/chatting/completeModal.tsx
  src/components/chatting/controlModal.tsx
  src/components/chatting/warningModal.tsx
  src/components/common/borderTextInputBox.tsx
  src/components/common/customTextInputBox.tsx
  src/components/commonComponents/oneButtonModal.tsx
  src/components/commonComponents/twoButtonModal.tsx
  src/components/myPage/favoriteRoom.tsx
  src/components/recommendRoom/sortTypeBottomSheet.tsx
  src/components/report/reportComponent.tsx
  src/components/schoolAuthentication/buttonTextInput.tsx
  src/components/userDetail/tableView.tsx
  src/hooks/api/mail.ts
  src/hooks/api/member.ts
  src/hooks/api/room.ts
  src/screens/chatting/chatRoom.tsx
  src/screens/editRoom/editRoom.tsx
  src/screens/joinRoom/joinRoom.tsx
  src/screens/myPage/favoriteUserRoom.tsx
  src/screens/myPage/inquiry.tsx
  src/screens/myPage/withdraw.tsx
  src/screens/recommendRoom/recommendRoom.tsx
  src/screens/roomDetail/roomDetail.tsx
  src/screens/schoolAuthentication/schoolAuthentication.tsx
  src/screens/search/userSearch.tsx
  src/screens/userDetail/userDetail.tsx
  src/zustand/room/room.ts
  src/zustand/room/type.ts
Labels: 🐞 FIX, 🎉 FEAT

#71 [COZY-450] 코드 오류 해결 및 QA
  src/assets/userDetail/phone.svg
  src/axios/axios.method.ts
  src/components/cozyHome/recommendRoom.tsx
  src/components/cozyHome/recommendRoomList.tsx
  src/components/myPage/favoriteUser.tsx
  src/components/recommendRoom/RoomComponent.tsx
  src/components/recommendRoom/roomComponent.tsx
  src/components/recommendRoom/sortTypeBottomSheet.tsx
  src/components/userDetail/listView.tsx
  src/components/userDetail/tableView.tsx
  src/components/userDetail/tableViewModal.tsx
  src/hooks/api/member.ts
  src/hooks/api/room-log.ts
  src/screens/chatting/chat.tsx
  src/screens/cozyHome/cozyHome.tsx
  src/screens/myPage/basicInfoUpdate.tsx
  src/screens/myPage/myPage.tsx
  src/screens/myPage/withdraw.tsx
  src/screens/notification/notification.tsx
  src/screens/roleNrule/roleNrule.tsx
  src/screens/signIn/signIn.tsx
  src/screens/userDetail/userDetail.tsx
  src/server/api/member.ts
  src/server/requestTypes/member.ts
  src/server/responseTypes/room-recommend.ts
  src/type/param/stack.ts
  src/type/userDetail/userDetail.ts
  tailwind.config.js
Labels: 🐞 FIX, 🎉 FEAT

#72 [COZY-422] FCM 클릭 시 화면 이동 구현 완료
  App.tsx
  AppInner.tsx
  android/app/src/main/AndroidManifest.xml
  index.js
  ios/cozymate/AppDelegate.mm
  src/config/deepLinkConfig.ts
  src/hooks/autoLogin.ts
  src/hooks/fcm.tsx
  src/hooks/notifee.tsx
  src/hooks/useFcm.tsx
  src/screens/main.tsx
  src/screens/myPage/myPage.tsx
  src/screens/signIn/signIn.tsx
  src/utils/fcm/convertAction.ts
  src/utils/fcm/deviceUtil.ts
  src/utils/fcm/fcmHandler.ts
  src/utils/fcm/fcmTokenUtil.ts
Labels: 🎉 FEAT
