Repository cozy-mate/cozymate-iOS, pull requests merged in 2024-11, with the labels that each got.

#56 [COZY-376] FCM 자동 로그인에 맞춰서 로직 변경
  AppInner.tsx
  index.js
  ios/cozymate.xcodeproj/project.pbxproj
  react-native-clean-build.sh
  src/components/feedView/commentList.tsx
  src/hooks/useFcm.tsx
  src/hooks/useInitFcm.tsx
  src/screens/cozyHome/cozyHome.tsx
  src/screens/main.tsx
  src/screens/myPage/myPage.tsx
  src/screens/myPage/withdraw.tsx
  src/screens/signIn/signIn.tsx
  src/utils/fcm/deviceUtil.ts
  src/utils/fcm/fcmHandler.ts
  src/utils/fcm/fcmTokenUtil.ts
  src/utils/mockData/exampleList.ts
Labels: 🐞 FIX, 🎉 FEAT

#58 [COZY-386] Role Request 수정 및 Suspense 추가
  index.js
  ios/cozymate/AppDelegate.mm
  ios/cozymate/Images.xcassets/AppIcon.appiconset/1024.png
  ios/cozymate/Images.xcassets/AppIcon.appiconset/120 1.png
  ios/cozymate/Images.xcassets/AppIcon.appiconset/120.png
  ios/cozymate/Images.xcassets/AppIcon.appiconset/180.png
  ios/cozymate/Images.xcassets/AppIcon.appiconset/40.png
  ios/cozymate/Images.xcassets/AppIcon.appiconset/58.png
  ios/cozymate/Images.xcassets/AppIcon.appiconset/60.png
  ios/cozymate/Images.xcassets/AppIcon.appiconset/80.png
  ios/cozymate/Images.xcassets/AppIcon.appiconset/87.png
  ios/cozymate/Images.xcassets/AppIcon.appiconset/Contents.json
  ios/cozymate/Images.xcassets/AppIcon.appiconset/cozymate.png
  src/assets/cozyHome/graySchoolIcon.svg
  src/assets/lottie/findRoomMate.json
  src/assets/lottie/lifestyle.json
  src/assets/lottie/schoolAuthentication.json
  src/components/cozyHome/noRoomComponent.tsx
  src/components/cozyHome/recommendRoom.tsx
  src/components/cozyHome/recommendRoomList.tsx
  src/components/cozyHome/recommendUser.tsx
  src/components/cozyHome/recommendationSection.tsx
  src/components/cozyHome/recommentUserList.tsx
  src/components/cozyHome/requestUserComponent.tsx
  src/components/cozyHome/roomComponent.tsx
  src/components/cozyHome/userComponent.tsx
  src/components/todoList/roleSelectMate.tsx
  src/components/userDetail/tableView.tsx
  src/hooks/api/member-stat.ts
  src/hooks/api/room.ts
  src/screens/cozyHome/cozyHome.tsx
  src/screens/createRoom/createRoom.tsx
  src/screens/main.tsx
  src/screens/myPage/myPage.tsx
  src/screens/recommendRoom/recommendRoom.tsx
  src/screens/roleNrule/createRoleNRule.tsx
  src/screens/roleNrule/editRoleAndRule.tsx
  src/screens/roomDetail/roomDetail.tsx
  src/screens/roomMate/roomMate.tsx
  src/screens/signIn/signIn.tsx
  src/screens/userDetail/userDetail.tsx
  src/server/api/room.ts
  src/server/requestTypes/role.ts
  src/server/responseTypes/member-stat.ts
  src/server/responseTypes/room.ts
Labels: 🎉 FEAT

#59 [COZY-390] 방 추천 API 변경 및 라이프스타일 없는 경우 코드 추가
  App.tsx
  AppInner.tsx
  ios/cozymate/LaunchScreen.storyboard
  src/assets/recommendRoom/downArrow.svg
  src/assets/roomMate/blueRightArrow.svg
  src/assets/userDetail/filledHeart.svg
  src/assets/userDetail/heart.svg
  src/assets/userDetail/message.svg
  src/components/common/advertisement.tsx
  src/components/cozyHome/recommendRoom.tsx
  src/components/cozyHome/recommendRoomList.tsx
  src/components/cozyHome/recommentUserList.tsx
  src/components/customCheckBox.tsx
  src/components/recommendRoom/RoomComponent.tsx
  src/components/recommendRoom/roomComponent.tsx
  src/components/roomMate/checkBoxContainer.tsx
  src/components/roomMate/noLifeStyleComponent.tsx
  src/components/roomMate/userComponent.tsx
  src/hooks/api/member-stat.ts
  src/hooks/api/room-recommend.ts
  src/hooks/api/room.ts
  src/screens/cozyHome/cozyHome.tsx
  src/screens/myPage/inquiry.tsx
  src/screens/myPage/withdraw.tsx
  src/screens/notification/notification.tsx
  src/screens/recommendRoom/recommendRoom.tsx
  src/screens/roomDetail/roomDetail.tsx
  src/screens/roomMate/dummyData.ts
  src/screens/roomMate/roomMate.tsx
  src/screens/search/roomSearch.tsx
  src/screens/search/userSearch.tsx
  src/screens/todoList/createTodo.tsx
  src/screens/todoList/todoList.tsx
  src/screens/userDetail/userDetail.tsx
  src/server/api/room-recommend.ts
  src/server/api/room.ts
  src/server/responseTypes/room-recommend.ts
  src/server/responseTypes/room.ts
  src/type/param/stack.ts
  src/zustand/room/room.ts
  src/zustand/room/type.ts
Labels: 🎉 FEAT

#60 [COZY-394] 프로필 변경 연결
  src/assets/cozyHome/chatIcon.svg
  src/assets/cozyHome/megaPhone.svg
  src/assets/cozyHome/notificationIcon.svg
  src/components/common/bottomButton.tsx
  src/components/commonComponents/oneButtonModal.tsx
  src/components/commonComponents/twoButtonModal.tsx
  src/components/cozyHome/createRoomModal.tsx
  src/components/cozyHome/myRoomComponent.tsx
  src/components/cozyHome/recommendRoom.tsx
  src/components/cozyHome/recommendRoomList.tsx
  src/components/cozyHome/recommentUserList.tsx
  src/components/cozyHome/requestRoomComponent.tsx
  src/components/cozyHome/requestUserComponent.tsx
  src/components/loading/loading.tsx
  src/components/myPage/majorSelect.tsx
  src/components/recommendRoom/RoomComponent.tsx
  src/components/recommendRoom/roomComponent.tsx
  src/hooks/api/favorite.ts
  src/hooks/api/mail.ts
  src/hooks/api/member-stat.ts
  src/hooks/api/member.ts
  src/hooks/api/room.ts
  src/hooks/api/university.ts
  src/screens/cozyHome/cozyHome.tsx
  src/screens/createRoom/completeCreate.tsx
  src/screens/editRoom/selectCharacterModal.tsx
  src/screens/myPage/basicInfoUpdate.tsx
  src/screens/myPage/myInfo.tsx
  src/screens/recommendRoom/recommendRoom.tsx
  src/screens/roomDetail/roomDetail.tsx
  src/screens/roomMate/roomMate.tsx
  src/screens/schoolAuthentication/schoolAuthentication.tsx
  src/screens/signIn/signIn.tsx
  src/screens/userDetail/userDetail.tsx
  src/server/api/mail.ts
  src/server/api/member.ts
  src/server/api/room.ts
  src/server/responseTypes/member-stat.ts
  src/server/responseTypes/member.ts
  src/server/responseTypes/room-recommend.ts
  src/zustand/member/member.ts
  src/zustand/member/type.ts
Labels: 🎉 FEAT

#61 [COZY-406] 재배포를 위한 코드 수정
  src/assets/lottie/lifestyle.json
  src/assets/lottie/roleNrule.json
  src/components/common/bottomButton.tsx
  src/components/common/chipSelectModal.tsx
  src/components/onBoard/univInfoSelect.tsx
  src/hooks/api/mail.ts
  src/hooks/api/member-stat.ts
  src/hooks/api/member.ts
  src/hooks/api/room.ts
  src/hooks/autoLogin.ts
  src/screens/cozyHome/cozyHome.tsx
  src/screens/editRoom/editRoom.tsx
  src/screens/editRoom/selectCharacterModal.tsx
  src/screens/lifeStyle/additionalInformation.tsx
  src/screens/lifeStyle/basicInformation.tsx
  src/screens/lifeStyle/essentialInformation.tsx
  src/screens/lifeStyle/onBoarding.tsx
  src/screens/myPage/myPage.tsx
  src/screens/notification/notification.tsx
  src/screens/roomDetail/roomDetail.tsx
  src/screens/schoolAuthentication/schoolAuthentication.tsx
  src/screens/signIn/signIn.tsx
  src/screens/userDetail/userDetail.tsx
  src/server/api/mail.ts
  src/server/api/room.ts
  src/server/requestTypes/member-stat.ts
  src/server/responseTypes/mail.ts
  src/server/responseTypes/room.ts
  src/type/param/stack.ts
  src/zustand/member-stat/type.ts
  src/zustand/member/member.ts
  src/zustand/room/room.ts
  src/zustand/room/type.ts
Labels: 🎉 FEAT

#62 [COZY-409] remove: 피드 제거, Recoil 제거
  .eslintrc
  App.tsx
  AppInner.tsx
  babel.config.js
  ios/Podfile.lock
  ios/cozymate.xcodeproj/project.pbxproj
  package.json
  src/components/feedMain/footer.tsx
  src/components/feedMain/header.tsx
  src/components/feedMain/postCard.tsx
  src/components/feedMain/postList.tsx
  src/components/feedView/commentCard.tsx
  src/components/feedView/commentList.tsx
  src/components/feedView/controlModal.tsx
  src/hooks/api/feed.ts
  src/hooks/api/post.ts
  src/recoil/recoil.ts
  src/screens/feed/feedCreate.tsx
  src/screens/feed/feedEdit.tsx
  src/screens/feed/feedMain.tsx
  src/screens/feed/feedView.tsx
  src/screens/main.tsx
  src/server/api/feed.ts
  src/server/api/post.ts
  src/server/requestTypes/feed.ts
  src/server/requestTypes/post.ts
  src/type/feed/feedType.ts
  src/type/feed/index.ts
  src/type/feed/postType.ts
  src/type/param/stack.ts
  tsconfig.json
  yarn.lock
Labels: ⚙️ CHORE, ⌦ REMOVE

#63 [COZY-412] 미니 QA 후 코드 수정
  src/assets/roomMate/coloredFilter.svg
  src/components/commonComponents/twoButtonModal.tsx
  src/components/cozyHome/recommendRoom.tsx
  src/components/roomMate/code.tsx
  src/components/roomMate/filteringModal.tsx
  src/components/roomMate/filteringModalItem.tsx
  src/components/roomMate/filteringOption.tsx
  src/components/todoList/daySelect.tsx
  src/hooks/api/member-stat.ts
  src/hooks/api/role.ts
  src/hooks/api/rule.ts
  src/hooks/api/todo.ts
  src/screens/cozyHome/cozyHome.tsx
  src/screens/lifeStyle/additionalInformation.tsx
  src/screens/lifeStyle/basicInformation.tsx
  src/screens/lifeStyle/essentialInformation.tsx
  src/screens/roleNrule/createRoleNRule.tsx
  src/screens/roleNrule/editRoleAndRule.tsx
  src/screens/roleNrule/roleNrule.tsx
  src/screens/roomMate/roomMate.tsx
  src/screens/schoolAuthentication/schoolAuthentication.tsx
  src/screens/signIn/signIn.tsx
  src/server/api/member-stat.ts
  src/server/requestTypes/member-stat.ts
  src/server/requestTypes/role.ts
  src/zustand/member-stat/member-stat.ts
  src/zustand/member-stat/type.ts
  src/zustand/rule/rule.ts
  src/zustand/rule/type.ts
Labels: 🎉 FEAT

#64 [COZY-416] QA 반영
  ios/Podfile.lock
  ios/cozymate/Images.xcassets/AppIcon.appiconset/Contents.json
  ios/cozymate/Images.xcassets/AppIcon.appiconset/cozymate.png
  ios/cozymate/Images.xcassets/AppIcon.appiconset/logo_ver2.png
  package.json
  src/components/cozyHome/myRoomComponent.tsx
  src/components/cozyHome/requestUserComponent.tsx
  src/components/myPage/favoriteRoom.tsx
  src/components/myPage/favoriteUser.tsx
  src/components/roomDetail/lifeStyleModal.tsx
  src/components/roomMate/filteringModal.tsx
  src/components/todoList/customCalendar.tsx
  src/hooks/api/member-stat.ts
  src/hooks/api/room.ts
  src/screens/cozyHome/cozyHome.tsx
  src/screens/createRoom/completeCreate.tsx
  src/screens/createRoom/createRoom.tsx
  src/screens/joinRoom/joinRoom.tsx
  src/screens/lifeStyle/additionalInformation.tsx
  src/screens/myPage/favoriteUserRoom.tsx
  src/screens/roleNrule/createRoleNRule.tsx
  src/screens/roleNrule/roleNrule.tsx
  src/screens/roomDetail/roomDetail.tsx
  src/screens/roomMain/roomMain.tsx
  src/screens/roomMate/roomMate.tsx
  src/screens/schoolAuthentication/schoolAuthentication.tsx
  src/screens/signIn/signIn.tsx
  src/screens/userDetail/userDetail.tsx
  src/utils/getLifeStyleIcon.tsx
  tailwind.config.js
  yarn.lock
Labels: 🐞 FIX, ⚙️ CHORE, 🎉 FEAT
